Repository sgm-capstone/SGMarket_Backend, pull requests merged in 2025-05, with the labels that each got.

#29 논리 삭제된 경매 글 필터링하여 보여주도록 변경
  src/main/java/shop/sgmarket/sgmarketbackend/auction/application/AuctionService.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/AuctionRepository.java
Labels: 🔨 Refactor

#31 액세스 토큰 발급 api 추가
  src/main/java/shop/sgmarket/sgmarketbackend/auth/api/AuthController.java
  src/main/java/shop/sgmarket/sgmarketbackend/auth/api/AuthDocs.java
  src/main/java/shop/sgmarket/sgmarketbackend/auth/application/AuthService.java
  src/main/java/shop/sgmarket/sgmarketbackend/auth/dto/RefreshTokenDto.java
  src/main/java/shop/sgmarket/sgmarketbackend/auth/dto/response/AccessTokenResponse.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/error/ErrorCode.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/filter/JwtAuthenticationFilter.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/security/JwtTokenProvider.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/util/CookieUtil.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/util/JwtUtil.java
Labels: ✨ Feature

#34 스웨거 접속 안되는 문제 해결
  src/main/java/shop/sgmarket/sgmarketbackend/auth/application/AuthService.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/util/CookieUtil.java
Labels: 🐞 Bug

#36 precision, scale 속성 제거
  src/main/java/shop/sgmarket/sgmarketbackend/auction/domain/Auction.java
  src/main/java/shop/sgmarket/sgmarketbackend/member/domain/MemberLocation.java
Labels: 🐞 Bug

#37 위도 경도 null 허용
  src/main/java/shop/sgmarket/sgmarketbackend/auction/domain/Auction.java
  src/main/java/shop/sgmarket/sgmarketbackend/member/domain/MemberLocation.java
Labels: 🐞 Bug

#39 경매 작성자의 다른 경매 목록 조회 기능 추가
  src/main/java/shop/sgmarket/sgmarketbackend/auction/api/AuctionController.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/api/AuctionDocs.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/application/AuctionService.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/AuctionRepository.java
Labels: ✨ Feature

#41 경매 좋아요 기능 구현
  src/main/java/shop/sgmarket/sgmarketbackend/auction/api/AuctionController.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/api/AuctionDocs.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/application/AuctionLikeService.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/domain/Auction.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/domain/AuctionLike.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/dto/response/AuctionInfoResponse.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/dto/response/AuctionToggleLikeResponse.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/AuctionLikeRepository.java
Labels: ✨ Feature

#45 입찰 기능 및 입찰 내역 조회 기능 구현
  src/main/java/shop/sgmarket/sgmarketbackend/auction/api/BidController.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/api/BidDocs.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/application/AuctionLikeService.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/application/AuctionService.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/application/BidService.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/domain/Auction.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/domain/AuctionStatus.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/domain/Bid.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/dto/request/AuctionRegisterRequest.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/dto/request/BidRegisterRequest.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/dto/response/AuctionInfoResponse.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/dto/response/BidInfoResponse.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/AuctionRepository.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/AuctionRepositoryCustom.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/AuctionRepositoryImpl.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/BidRepository.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/error/ErrorCode.java
Labels: 📃 Docs, ✨ Feature

#47 경매 입찰 기능 구현
  src/main/java/shop/sgmarket/sgmarketbackend/auction/api/BidController.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/application/BidService.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/domain/Auction.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/BidRepository.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/error/ErrorCode.java
Labels: ✨ Feature

#49 회원 정보 조회 기능 구현
  src/main/java/shop/sgmarket/sgmarketbackend/auction/api/BidController.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/api/BidDocs.java
  src/main/java/shop/sgmarket/sgmarketbackend/member/api/MemberController.java
  src/main/java/shop/sgmarket/sgmarketbackend/member/api/MemberDocs.java
  src/main/java/shop/sgmarket/sgmarketbackend/member/application/MemberService.java
  src/main/java/shop/sgmarket/sgmarketbackend/member/dto/response/MemberInfoResponse.java
Labels: 📃 Docs, ✨ Feature, 🔨 Refactor

#51 용량 큰 이미지 업로드 오류 해결
  src/main/resources/application-cloud.yml
Labels: 🐞 Bug

#53 경매 최대 제시가 기능 구현
  src/main/java/shop/sgmarket/sgmarketbackend/auction/api/BidController.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/api/BidDocs.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/application/BidService.java
Labels: ✨ Feature

#55 최대 입찰가 조회 기능 추가
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/BidRepository.java
Labels: ✨ Feature

#56 경매 시세 조회 기능 구현
  src/main/java/shop/sgmarket/sgmarketbackend/auction/api/AuctionController.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/api/AuctionDocs.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/application/AuctionService.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/application/BidService.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/domain/Auction.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/domain/Item.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/domain/PriceHistory.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/dto/response/AuctionInfoResponse.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/dto/response/PriceHistoryInfoResponse.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/AuctionRepository.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/AuctionRepositoryCustom.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/AuctionRepositoryImpl.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/ItemRepository.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/PriceHistoryRepository.java
Labels: ✨ Feature

#57 PriceHistory Id 생성 전략 지정
  src/main/java/shop/sgmarket/sgmarketbackend/auction/domain/PriceHistory.java
Labels: 🔨 Refactor

#59 경매 랜덤 조회 기능 구현
  src/main/java/shop/sgmarket/sgmarketbackend/auction/api/AuctionController.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/api/AuctionDocs.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/application/AuctionService.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/AuctionRepository.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/AuctionRepositoryCustom.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/AuctionRepositoryImpl.java
Labels: ✨ Feature

#62 경매 자동 낙찰 기능 구현
  src/main/java/shop/sgmarket/sgmarketbackend/auction/application/BidService.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/AuctionRepository.java
  src/main/java/shop/sgmarket/sgmarketbackend/auction/scheduler/AuctionScheduler.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/config/SchedulerConfig.java
Labels: ✨ Feature

#65 경매 수정 시 이미지 업로드 안 해도 수정되도록 변경
  src/main/java/shop/sgmarket/sgmarketbackend/auction/application/AuctionService.java
Labels: 🐞 Bug

#68 portone를 이용한 상품 결제 기능 추가
  build.gradle
  src/main/java/shop/sgmarket/sgmarketbackend/auction/repository/PriceHistoryRepository.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/config/PortOneConfig.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/config/SecurityConfig.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/error/ErrorCode.java
  src/main/java/shop/sgmarket/sgmarketbackend/order/api/OrderController.java
  src/main/java/shop/sgmarket/sgmarketbackend/order/application/OrderService.java
  src/main/java/shop/sgmarket/sgmarketbackend/order/domain/Order.java
  src/main/java/shop/sgmarket/sgmarketbackend/order/domain/OrderItem.java
  src/main/java/shop/sgmarket/sgmarketbackend/order/domain/repository/OrderRepository.java
  src/main/java/shop/sgmarket/sgmarketbackend/order/dto/request/OrderRequest.java
  src/main/java/shop/sgmarket/sgmarketbackend/order/dto/response/OrderItemResponse.java
  src/main/java/shop/sgmarket/sgmarketbackend/order/dto/response/OrderResponse.java
  src/main/java/shop/sgmarket/sgmarketbackend/payment/api/PaymentController.java
  src/main/java/shop/sgmarket/sgmarketbackend/payment/api/PaymentWebhookController.java
  src/main/java/shop/sgmarket/sgmarketbackend/payment/api/dto/request/PaymentCallbackReqDto.java
  src/main/java/shop/sgmarket/sgmarketbackend/payment/api/dto/request/PaymentWebhookDto.java
  src/main/java/shop/sgmarket/sgmarketbackend/payment/api/dto/response/PaymentResDto.java
  src/main/java/shop/sgmarket/sgmarketbackend/payment/application/PaymentService.java
  src/main/java/shop/sgmarket/sgmarketbackend/payment/domain/Payment.java
  src/main/java/shop/sgmarket/sgmarketbackend/payment/domain/Status.java
  src/main/java/shop/sgmarket/sgmarketbackend/payment/domain/repository/PaymentRepository.java
  src/main/resources/application.yml
Labels: ✨ Feature
