Repository sgm-capstone/SGMarket_Backend, pull requests merged in 2025-03, with the labels that each got.

#2 프로젝트 생성 및 기본 설정
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/shop/sgmarket/sgmarketbackend/SgMarketBackendApplication.java
  src/main/resources/applicaiton-test.yml
  src/main/resources/application-datasource.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/shop/sgmarket/sgmarketbackend/SgMarketBackendApplicationTests.java
Labels: ⚙ Setting

#4 글로벌 설정 및 예외 처리, 응답 템플릿 구현
  build.gradle
  src/main/java/shop/sgmarket/sgmarketbackend/global/config/JpaAuditingConfig.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/config/QuerydslConfig.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/config/RestClientConfig.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/domain/BaseTimeEntity.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/domain/Status.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/error/ErrorCode.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/error/ErrorResponse.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/error/exception/CustomException.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/error/exception/GlobalExceptionHandler.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/response/ApiResponse.java
Labels: ✨ Feature, ⚙ Setting

#6 CI/CD 파이프라인 구축 및 자동 배포 설정
  .github/workflows/deploy.yml
  Dockerfile
Labels: 🌏 Devops, ⚙ Setting

#9 swagger 설정 추가
  build.gradle
  src/main/java/shop/sgmarket/sgmarketbackend/global/config/SwaggerConfig.java
  src/main/java/shop/sgmarket/sgmarketbackend/global/properties/SwaggerProperties.java
  src/main/resources/application.yml
Labels: ✨ Feature, ⚙ Setting
